[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
#v4.9.5

solc_version = "0.8.19"
optimizer = true
optimizer_runs = 500


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
